#!/usr/bin/env python3
"""
export_uluru_csv.py — Extract OpenFOAM results to website CSV format.

Run AFTER the UGA simulations complete and results are downloaded.
Generates terrain + wind CSVs at 100m and 500m from CFD results,
plus the 5km analytical CSVs (already generated by setup script).

Usage:
    conda run -n downscalewind python notebooks/export_uluru_csv.py

Expects:
    data/website/uluru/cfd/case_{100m,500m}_{cross,along}/500/U
    data/website/uluru/cfd/case_{100m,500m}_{cross,along}/0/{Cx,Cy,Cz}

Output:
    data/website/uluru/
        terrain_100m.csv  terrain_500m.csv
        wind_cross_100m.csv  wind_along_100m.csv
        wind_cross_500m.csv  wind_along_500m.csv
"""
from __future__ import annotations

import math
import re
from pathlib import Path

import numpy as np
from pyproj import Transformer
from scipy.interpolate import griddata

# ── Constants ─────────────────────────────────────────────────────────────────

ULURU_LAT = -25.3444
ULURU_LON = 131.0369
DOMAIN_HALF_KM = 10

UTM_ZONE = int((ULURU_LON + 180) / 6) + 1  # 52
UTM_EPSG = f"EPSG:327{UTM_ZONE:02d}"       # EPSG:32752

ROOT = Path(__file__).resolve().parents[1]
OUTDIR = ROOT / "data" / "website" / "uluru"
CFD_DIR = OUTDIR / "cfd"
DEM_TIF = OUTDIR / "copdem_uluru_30m.tif"

# Reference height for surface wind extraction [m AGL]
Z_REF_AGL = 10.0
Z_TOL = 30.0  # accept cells within [Z_REF - Z_TOL, Z_REF + Z_TOL]

RESOLUTIONS = {"100m": 100, "500m": 500}
CONDITIONS = ["cross", "along"]


# ── OpenFOAM field readers ────────────────────────────────────────────────────

def read_of_scalar(filepath: Path) -> np.ndarray:
    """Read an OpenFOAM volScalarField (Cx, Cy, Cz, etc.)."""
    text = filepath.read_text()
    # Find the internalField block
    match = re.search(r'internalField\s+nonuniform\s+List<scalar>\s+(\d+)\s*\((.*?)\)',
                      text, re.DOTALL)
    if not match:
        raise ValueError(f"Cannot parse scalar field: {filepath}")
    values = match.group(2).strip().split('\n')
    return np.array([float(v.strip()) for v in values if v.strip()])


def read_of_vector(filepath: Path) -> np.ndarray:
    """Read an OpenFOAM volVectorField (U). Returns (N, 3) array."""
    text = filepath.read_text()
    # Find the count
    match = re.search(r'internalField\s+nonuniform\s+List<vector>\s+(\d+)', text)
    if not match:
        raise ValueError(f"Cannot parse vector field: {filepath}")
    n = int(match.group(1))
    # Find the opening ( after the count
    start = text.index('(', match.end()) + 1
    # Extract all (x y z) tuples
    rows = re.findall(r'\(([^()]+)\)', text[start:start + n * 60])
    if len(rows) < n:
        # Broader search
        end = text.index(')', text.index(')', start + n * 20) + 1)
        rows = re.findall(r'\(([^()]+)\)', text[start:end])
    arr = np.array([[float(x) for x in row.split()] for row in rows[:n]])
    return arr


# ── Terrain extraction from DEM ───────────────────────────────────────────────

def generate_terrain_csv(dx_m: float, label: str) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Generate terrain CSV from COP-DEM at target resolution."""
    import rasterio
    from scipy.interpolate import RegularGridInterpolator

    deg_lat = 111_320
    deg_lon = deg_lat * math.cos(math.radians(abs(ULURU_LAT)))

    with rasterio.open(DEM_TIF) as src:
        data = src.read(1)
        tf = src.transform
    lons = np.array([tf.c + (j + 0.5) * tf.a for j in range(data.shape[1])])
    lats = np.array([tf.f + (i + 0.5) * tf.e for i in range(data.shape[0])])

    half_lat = DOMAIN_HALF_KM / 111.32
    half_lon = DOMAIN_HALF_KM / (111.32 * math.cos(math.radians(abs(ULURU_LAT))))

    lon_t = np.arange(ULURU_LON - half_lon, ULURU_LON + half_lon + 0.001, dx_m / deg_lon)
    lat_t = np.arange(ULURU_LAT + half_lat, ULURU_LAT - half_lat - 0.001, -dx_m / deg_lat)

    interp = RegularGridInterpolator(
        (lats[::-1], lons), data[::-1],
        method="linear", bounds_error=False, fill_value=None,
    )
    lon_g, lat_g = np.meshgrid(lon_t, lat_t)
    z = interp((lat_g, lon_g))
    if np.any(np.isnan(z)):
        z[np.isnan(z)] = np.nanmean(z)

    # Write CSV
    csv_path = OUTDIR / f"terrain_{label}.csv"
    with open(csv_path, "w") as f:
        f.write("lon,lat,z\n")
        for i in range(len(lat_t)):
            for j in range(len(lon_t)):
                f.write(f"{lon_t[j]:.6f},{lat_t[i]:.6f},{z[i, j]:.1f}\n")

    print(f"  {csv_path.name}: {len(lat_t)}x{len(lon_t)} = {len(lat_t)*len(lon_t)} pts")
    return lon_t, lat_t, z


# ── Wind extraction from OF results ──────────────────────────────────────────

def extract_wind_csv(
    case_dir: Path,
    lon_grid: np.ndarray,
    lat_grid: np.ndarray,
    terrain_z: np.ndarray,
    label: str,
    cond: str,
) -> None:
    """Extract near-surface wind from OF case and write CSV."""
    # Read cell centres
    zero_dir = case_dir / "0"
    cx = read_of_scalar(zero_dir / "Cx")
    cy = read_of_scalar(zero_dir / "Cy")
    cz = read_of_scalar(zero_dir / "Cz")

    # Read velocity at final time step
    time_dirs = sorted(
        [d for d in case_dir.iterdir() if d.is_dir() and d.name.isdigit()],
        key=lambda d: int(d.name),
    )
    if not time_dirs:
        print(f"  WARNING: No time directories in {case_dir.name}, skipping")
        return
    final_dir = time_dirs[-1]
    u_vec = read_of_vector(final_dir / "U")

    print(f"  {case_dir.name}: {len(cx)} cells, time={final_dir.name}")

    # Convert local coords to lon/lat
    to_utm = Transformer.from_crs("EPSG:4326", UTM_EPSG, always_xy=True)
    to_wgs = Transformer.from_crs(UTM_EPSG, "EPSG:4326", always_xy=True)
    x0_utm, y0_utm = to_utm.transform(ULURU_LON, ULURU_LAT)

    cell_lon, cell_lat = to_wgs.transform(cx + x0_utm, cy + y0_utm)

    # Compute z_AGL using a simple approach:
    # For each cell, find the minimum z in its vertical column → terrain height
    # Approximate: bin by (x, y) and find column min z
    # Simpler: use the terrain DEM interpolated at cell positions
    from scipy.interpolate import RegularGridInterpolator
    import rasterio

    with rasterio.open(DEM_TIF) as src:
        dem_data = src.read(1)
        tf = src.transform
    dem_lons = np.array([tf.c + (j + 0.5) * tf.a for j in range(dem_data.shape[1])])
    dem_lats = np.array([tf.f + (i + 0.5) * tf.e for i in range(dem_data.shape[0])])

    terrain_interp = RegularGridInterpolator(
        (dem_lats[::-1], dem_lons), dem_data[::-1],
        method="linear", bounds_error=False, fill_value=500.0,
    )
    terrain_at_cells = terrain_interp((cell_lat, cell_lon))
    z_agl = cz - terrain_at_cells

    # Select near-surface cells (z_AGL ~ 10m)
    mask = (z_agl > Z_REF_AGL - Z_TOL) & (z_agl < Z_REF_AGL + Z_TOL)
    if mask.sum() < 10:
        # Fallback: take lowest 10% of cells
        z_thresh = np.percentile(z_agl[z_agl > 0], 15)
        mask = (z_agl > 0) & (z_agl < z_thresh)
        print(f"    Using fallback: {mask.sum()} cells below {z_thresh:.0f}m AGL")
    else:
        print(f"    {mask.sum()} cells near {Z_REF_AGL}m AGL")

    # Interpolate onto regular grid using griddata
    points = np.column_stack([cell_lon[mask], cell_lat[mask]])
    lon_g, lat_g = np.meshgrid(lon_grid, lat_grid)
    target = np.column_stack([lon_g.ravel(), lat_g.ravel()])

    u_interp = griddata(points, u_vec[mask, 0], target, method="linear")
    v_interp = griddata(points, u_vec[mask, 1], target, method="linear")
    w_interp = griddata(points, u_vec[mask, 2], target, method="linear")

    # Fill NaN with nearest
    nan_mask = np.isnan(u_interp)
    if nan_mask.any():
        u_nn = griddata(points, u_vec[mask, 0], target, method="nearest")
        v_nn = griddata(points, u_vec[mask, 1], target, method="nearest")
        w_nn = griddata(points, u_vec[mask, 2], target, method="nearest")
        u_interp[nan_mask] = u_nn[nan_mask]
        v_interp[nan_mask] = v_nn[nan_mask]
        w_interp[nan_mask] = w_nn[nan_mask]

    u_2d = u_interp.reshape(lon_g.shape)
    v_2d = v_interp.reshape(lon_g.shape)
    w_2d = w_interp.reshape(lon_g.shape)

    # Note: OF U is in local coords (x=east, y=north in UTM)
    # For the web viewer, u=east, v=north — same convention ✓

    # Write CSV
    csv_path = OUTDIR / f"wind_{cond}_{label}.csv"
    with open(csv_path, "w") as f:
        f.write("lon,lat,u,v,w\n")
        for i in range(len(lat_grid)):
            for j in range(len(lon_grid)):
                f.write(f"{lon_grid[j]:.6f},{lat_grid[i]:.6f},"
                        f"{u_2d[i,j]:.2f},{v_2d[i,j]:.2f},{w_2d[i,j]:.2f}\n")

    spd = np.sqrt(u_2d**2 + v_2d**2)
    print(f"    -> {csv_path.name}: speed [{spd.min():.1f}, {spd.max():.1f}] m/s")


# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    print("=" * 60)
    print("Export Uluru CFD results to website CSVs")
    print("=" * 60)

    # Terrain CSVs (from DEM, no OF needed)
    print("\n--- Terrain CSVs ---")
    grids = {}
    for label, dx in RESOLUTIONS.items():
        lon_t, lat_t, z = generate_terrain_csv(dx, label)
        grids[label] = (lon_t, lat_t, z)

    # Wind CSVs (from OF results)
    print("\n--- Wind CSVs ---")
    for label in RESOLUTIONS:
        lon_t, lat_t, z = grids[label]
        for cond in CONDITIONS:
            case_dir = CFD_DIR / f"case_{label}_{cond}"
            if not case_dir.exists():
                print(f"  {case_dir.name}: NOT FOUND, skipping")
                continue
            # Check if solved
            time_dirs = [d for d in case_dir.iterdir()
                         if d.is_dir() and d.name.isdigit()]
            if not time_dirs:
                print(f"  {case_dir.name}: not solved yet, skipping")
                continue
            extract_wind_csv(case_dir, lon_t, lat_t, z, label, cond)

    # Summary
    print("\n" + "=" * 60)
    print("Files:")
    print("=" * 60)
    for p in sorted(OUTDIR.glob("*.csv")):
        print(f"  {p.name:30s} {p.stat().st_size/1024:8.1f} KB")


if __name__ == "__main__":
    main()
